### PR TITLE
Eurostat bugs

### PR DESCRIPTION
**Pull request by MichelJuillard**
Fixes several bugs and expands test_eurostat.py:
- attributes key list are now forced to be lower case
- asbence of OBS_VALUE attribute in Series is recored as a missing value ("") in MongoDB

### CODE REVIEW

**Comment by mmalter** [comment]
Je crois que l'échec du build était attendu non? On devrait pouvoir merge.

**Comment by MichelJuillard** [comment]
Non les tests passent chez moi
Je regarde plus tard
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by MichelJuillard** [comment]
Non les tests passent chez moi
Je regarde plus tard

**Comment by MichelJuillard** [comment]
@mmalter It looks as if I had mixed-up the test_eurostat.py versions when doing the different PRs. Let me see tomorrow if I can easily fix it

**Comment by MichelJuillard** [comment]
@mmalter tu peux merger maintenant si tu es d'accord

**Pull request merged**
